<a href="https://colab.research.google.com/github/gineeeegg/course_3.0/blob/main/Numpy_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## $\Large{Numpy\; 練習題}$

In [1]:
import numpy as np

---
# 1-Dimension Array

## Exercise 1
使用np.arrange 函數創建一個數值從10到49的一維陣列

In [ ]:
ar = np.arange(10,50)
ar
print(ar.shape)

(40,)


## Exercise 2
請建立一個陣列，裡頭包含0~101中所有完全平方數(ex. 1, 4, 9...)

In [ ]:
ar2 = np.array([i**2 for i in range(11)])
print(ar2)

[  0   1   4   9  16  25  36  49  64  81 100]


## Exercise 3
反轉陣列x使得陣列內的元素從尾排到頭

In [ ]:
x = np.array([2, 0, 3, 1, 4, 7])

In [ ]:
print(x[::-1])

[7 4 1 3 0 2]


## Exercise 4
將x陣列內數值介於3到8(包含3和8)的元素取負號

In [2]:
X = np.array([6, 2, 8, 3, 0, 1])

In [4]:
#condition1 = X >= 3 #& X <= 8
#condition2 = X <= 8
#X[(condition1 & condition2)] *= -1 
X[(X >= 3) & (X <= 8)] *= -1
print(X)

[-6  2 -8 -3  0  1]


## Exercise 5
創建一個長度為10的隨機數字陣列，並且將最大值取代為0

In [ ]:
x = np.random.randn(10)
print(x)
x[np.argmax(x)] = 0
print(x)

[-1.72049057 -2.18231012 -0.29823835  0.11573193 -0.1783734  -1.41369157
  0.97742516 -1.8290369   0.28203201 -0.52437918]
[-1.72049057 -2.18231012 -0.29823835  0.11573193 -0.1783734  -1.41369157
  0.         -1.8290369   0.28203201 -0.52437918]


## Exercise 6
從陣列x中取出符合以下條件的子集

(1) 不能被 3 整除

(2) 可以被 3 整除

(3) 可以被 3 或 5 整除

In [ ]:
x = np.array([3, 4, 6, 10, 24, 89, 45, 43, 46, 99, 100])

In [ ]:
x1 = x[(x % 3 != 0)]
print(x1)
x2 = x[(x % 3 == 0)]
print(x2)
x3 = x[(x % 3 == 0) | (x % 5 == 0)]
print(x3)

[  4  10  89  43  46 100]
[ 3  6 24 45 99]
[  3   6  10  24  45  99 100]


## Exercise 7
使用np.arange建立從2019年1月到12月共12個月的陣列資料

範例結果如下
<img src='https://i.imgur.com/XrH8VCs.png'/>

In [ ]:
np.arange('2019-01', '2020-01', dtype='datetime64[M]')

array(['2019-01', '2019-02', '2019-03', '2019-04', '2019-05', '2019-06',
       '2019-07', '2019-08', '2019-09', '2019-10', '2019-11', '2019-12'],
      dtype='datetime64[M]')

---
# n-Dimension Array

## Exercise 8
請以ndim與shape兩個用法印出陣列x的維度數目與各維度的長度

In [ ]:
x = np.array([[[[[[[[[[[[[[[[[5, 4, 3, 2, 1]]]], [[[[10, 9, 8, 7, 6]]]]]]]]]]]]]]]]])

In [ ]:
print(x.shape)
print(x.ndim)

(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 5)
17


## Exercise 9
使用np.random.random 函數創建一個3x3x3的陣列

In [ ]:
x = np.random.random((3,3,3))
x

array([[[0.17624782, 0.73992397, 0.93247223],
        [0.20537924, 0.41155046, 0.82639286],
        [0.20856136, 0.33378151, 0.94435457]],

       [[0.17954599, 0.32682286, 0.13086319],
        [0.99261754, 0.61189656, 0.62732465],
        [0.22623779, 0.06155423, 0.11796183]],

       [[0.09372759, 0.49544133, 0.76337994],
        [0.35811429, 0.4995744 , 0.2830303 ],
        [0.85537726, 0.39543522, 0.46733451]]])

## Exercise 10
創建一個5x5且數值介於0到4之間的整數陣列

In [ ]:
np.random.randint(0, 4, size=(5, 5))

array([[1, 2, 0, 1, 1],
       [3, 2, 1, 3, 0],
       [1, 3, 1, 3, 2],
       [3, 0, 2, 0, 1],
       [3, 3, 2, 1, 1]])

## Exercise 11
創建一個擁有隨機數值且形狀為10x10的陣列，並且使用np.min 和 np.max兩函數找出陣列中的最大值/最小值

In [ ]:
x = np.random.random(size=(10,10))
print(x)
print(np.min(x))
print(np.max(x))

## Exercise 12
使用reshape函數將陣列x轉成最後一個維度的長度為1且第一個維度為3的3維陣列

In [ ]:
x = np.arange(9)

In [ ]:
x1 = x.reshape(3,3)
print(x1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## Exercise 13
請針對x陣列中的每欄資料做累積加總

註：加總後的陣列數值將為 [[2, 6, 3], [7, 15, 4]]

In [ ]:
x = np.array([2, 6, 3, 5, 9, 1]).reshape(2, -1)
x

array([[2, 6, 3],
       [5, 9, 1]])

In [ ]:
np.cumsum(x, axis=0)

array([[ 2,  6,  3],
       [ 7, 15,  4]])

## Exercise 14
陣列標準化: 將x陣列內所有的元素除以x陣列內元素的最大值

In [ ]:
x = np.random.randn(6).reshape(2, 3)

In [ ]:
print(x)
x1 = np.max(x)
print(x1)
xd = x/x1
print(xd)

[[-0.53360485 -0.08185162  1.47509934]
 [-0.01873699 -1.30633929 -1.06762489]]
1.4750993447045373
[[-0.36174164 -0.05548889  1.        ]
 [-0.01270219 -0.88559411 -0.72376474]]


## Exercise 15
請計算出x陣列中相鄰數字的差異並同樣存成np.array型態

註：由於x陣列有6個數字，因此相鄰數字的差異共會有5個數值，依序為 [-151, 224, -158, -88, 572]

In [6]:
x = np.array([183, 32, 256, 98, 10, 582])

In [15]:
x1 = np.array([x[i+1]-x[i] for i in range(len(x)-1)])
#x1 = x[1:6] - x[0:5] #解2
#x1 = x[1:] - x[:-1] 解3
x1

array([-151,  224, -158,  -88,  572])

## Exercise 16
請將x陣列中所有數值可被3整除的元素索引列出

註：由於x為二維陣列，單一個元素的索引會有兩個數字(ex.[1, 0])

In [ ]:
x = np.arange(20).reshape(4, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
np.argwhere(x % 3 == 0)

array([[0, 0],
       [0, 3],
       [1, 1],
       [1, 4],
       [2, 2],
       [3, 0],
       [3, 3]])

## Exercise 17
使用np.pad 函數在陣列x外圍加一層0，使得原本3x3的陣列變為5x5

In [16]:
x = np.ones(shape=(3, 3))

In [23]:
x1 = np.pad(x,1,mode='constant',constant_values = 0)
x1

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

## Exercise 18
計算x與y兩兩元素的乘積並做加總(答案應為32)

註：上述的做法其實就是矩陣內積，因此有超過兩種以上的作法可以計算出此答案，大家可以試試看自己會幾種

In [26]:
x = np.array([[1, 2, 3]])
y = np.array([[4, 5, 6]])

In [29]:
c1 = np.matmul(x,y.T)
print(c1)
c2 = np.dot(x,y.T)
print(c2)

[[32]]
[[32]]


## Exercise 19
使用np.concatenate函數將陣列x與陣列y合併在一起，使其與```np.append(x, y, axis = 1)```結果相同

In [30]:
x = np.array([[1, 2, 3]])
y = np.array([[4, 5, 6]])

np.append(x, y, axis=1)

array([[1, 2, 3, 4, 5, 6]])

In [33]:
xy = np.concatenate((x,y),axis = 1)
xy

array([[1, 2, 3, 4, 5, 6]])

### 請參考 [100-numpy-exercises](https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb) 做更多 numpy 的操作練習